// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh4LxLluTiRmRUOHOCJs73yA-PP3CySy4',
    appId: '1:1097610978951:web:e674a65a1a2c6ac8c63a22',
    messagingSenderId: '1097610978951',
    projectId: 'evenza-3e3f8',
    authDomain: 'evenza-3e3f8.firebaseapp.com',
    storageBucket: 'evenza-3e3f8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz-XCF6erNQLFt3uBL7g0IpuFJox56dGs',
    appId: '1:1097610978951:android:8b222ce1981f1bb6c63a22',
    messagingSenderId: '1097610978951',
    projectId: 'evenza-3e3f8',
    storageBucket: 'evenza-3e3f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJSKE0A93IDRcgsywKXGVGaao6awGbRiQ',
    appId: '1:1097610978951:ios:613b60a1f72fd18bc63a22',
    messagingSenderId: '1097610978951',
    projectId: 'evenza-3e3f8',
    storageBucket: 'evenza-3e3f8.appspot.com',
    iosBundleId: 'com.example.evenza',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJSKE0A93IDRcgsywKXGVGaao6awGbRiQ',
    appId: '1:1097610978951:ios:53485ecff925198dc63a22',
    messagingSenderId: '1097610978951',
    projectId: 'evenza-3e3f8',
    storageBucket: 'evenza-3e3f8.appspot.com',
    iosBundleId: 'com.example.evenza.RunnerTests',
  );
}
